import struct
import sys

from collections import namedtuple
from os import path

DmaEntry = namedtuple('DmaEntry', ["vrom_start", "vrom_end", "rom_start", "rom_end"])

def parse_dmatable(rom):
    dmatable_start = 0x00007430
    entries = []
    offset = dmatable_start
    y = 0

    while True:
        vrom_start, vrom_end, rom_start, rom_end = struct.unpack('>4i', rom[offset:offset+16])

        if vrom_start >= vrom_end:
            break

        entries.append(DmaEntry(vrom_start, vrom_end, rom_start, rom_end))
        offset += 16
    
    return entries

def write_file(out, variables):
    out.write("""
////////////////////////////////////////////////////////////////////////////////
// Do not edit this file, it is auto-generated by variables.py                //
//                                                                            //
// It contains variable specific to the hooking point, init code and the      //
// memory layout of the patch                                                 //
////////////////////////////////////////////////////////////////////////////////

""")
    for key, value in variables.items():
        if type(value) == int:
            out.write(f"constant {key} = ${value:X}\n")
        if type(value) == str:
            out.write(f"constant {key} = {value}\n")
    
def longest_run_of_zeroes(binary_data):
    cur = 0
    start = 0
    nops = 0
    largest_nops = 0

    while cur < len(binary_data):
        value, = struct.unpack('>i', binary_data[cur:cur+4])
        if value == 0:
            nops += 1
        else:
            if nops > largest_nops:
                largest_nops = nops
                start = cur - (nops*4)
            
            nops = 0
        
        cur += 4

    return largest_nops, start

def main(romfile, outfile):
    try:
        with open(romfile, "rb") as file:
            binary_data = file.read()
    except FileNotFoundError:
        print("Error: The file was not found.")
    except Exception as e:
        print(f"An error occurred: {e}")


    dmatable = parse_dmatable(rom=binary_data)
    dmadata = dmatable[2]
    code_file = dmatable[27]

    dmadata_index = len(dmatable)
    sc64_file_vrom = dmatable[-1].vrom_end
    _, init_code_offset = longest_run_of_zeroes(binary_data[code_file.vrom_start : code_file.vrom_end])

    variables = {
        "code_rom":             code_file.vrom_start,       # Location of code file in ROM,
        "code_ram":             0x800110A0,                 # Location of code file in RAM
        "dmadata_index":        dmadata_index,              # Entry in dma table to add our new file to
        "dmadata_vrom":         dmadata.vrom_start,         # Entry in dma table to add our new file to
        "hook_point":           0x800A1F74,                 # Instruction to replace to call our code
        "init_code_offset":     init_code_offset,           # Offset in code file where to put our init code
        "sc64_file_vrom":       sc64_file_vrom,             # Location of our patch in vrom
        "sc64_file_vram":       0x80500000,                 # Location to copy our code in VRAM
        "sc64_stack_context":   "sc64_file_vram + $8000",
        "sc64_stack_start":     "sc64_stack_context + $100",
        "sc64_stack_end":       "sc64_stack_start + $500",
        "os_thread_pointer":    "sc64_stack_end + $200"

    }

    with open(outfile, 'w') as f:
        write_file(f, variables)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Missing argument(s)")
        exit(-1)
    
    main(romfile=path.abspath(sys.argv[1]), outfile=path.abspath(sys.argv[2]))




